# Pyflakes (F)
# pycodestyle (E)
# flake8-bugbear (B)
# isort (I)
# flake8-builtins (A)
# pep8-naming (N)
# Warning (W)
# flake8-print (T20)
# flake8-annotations (ANN)
lint.select = [
    "F",
    "E",
    "B",
    "I",
    "A",
    "N",
    "W",
    "T20",
    "ANN",
]

lint.ignore = ["B008", "ANN401"]

line-length = 120

target-version = "py311"

lint.unfixable = []
